---
dependency:
  name: galaxy

driver:
  name: default
platforms:
  - name: localhost
    groups: [test_local]

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  env:
    ANSIBLE_ROLES_PATH: "../../../roles"
  